=== eplugin-io/spinx/schemas/PresetTheme.schema.json
{
  "$ref": "#/definitions/PresetTheme",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "AnnouncementEncourageMessages": {
      "additionalProperties": false,
      "properties": {
        "discount": {
          "type": "string"
        },
        "discountWithMinOrder": {
          "type": "string"
        },
        "freeGift": {
          "type": "string"
        },
        "freeShip": {
          "type": "string"
        },
        "freeShipWithMaxAmount": {
          "type": "string"
        },
        "freeShipWithMaxAmountAndMinOrder": {
          "type": "string"
        },
        "freeShipWithMinOrder": {
          "type": "string"
        },
        "helperText": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "AnnouncementMessages": {
      "additionalProperties": false,
      "properties": {
        "countDownToClose": {
          "type": "string"
        },
        "countDownToLaunch": {
          "type": "string"
        },
        "readyToSpin": {
          "type": "string"
        },
        "upcomingEvent": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "AnnouncementPosition": {
      "enum": [
        "top",
        "bottom"
      ],
      "type": "string"
    },
    "BackgroundImage": {
      "additionalProperties": false,
      "properties": {
        "main": {
          "$ref": "#/definitions/StorageObject"
        },
        "mobile": {
          "$ref": "#/definitions/StorageObject"
        }
      },
      "type": "object"
    },
    "BasePopup": {
      "additionalProperties": false,
      "properties": {
        "backgroundColor": {
          "type": "string"
        },
        "description": {
          "$ref": "#/definitions/ElementObject"
        },
        "fontFamily": {
          "type": "string"
        },
        "footer": {
          "$ref": "#/definitions/ElementObject"
        },
        "helper": {
          "$ref": "#/definitions/ElementObject"
        },
        "linkButton": {
          "$ref": "#/definitions/ElementObject"
        },
        "primaryButton": {
          "$ref": "#/definitions/ButtonElement"
        },
        "secondaryButton": {
          "$ref": "#/definitions/ButtonElement"
        },
        "textInput": {
          "$ref": "#/definitions/TextInputElement"
        },
        "title": {
          "$ref": "#/definitions/ElementObject"
        }
      },
      "type": "object"
    },
    "ButtonElement": {
      "additionalProperties": false,
      "properties": {
        "backgroundColor": {
          "type": "string"
        },
        "color": {
          "type": "string"
        },
        "size": {
          "type": "number"
        },
        "weight": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "ConfirmationForm": {
      "additionalProperties": false,
      "properties": {
        "confirmButton": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "dismissButton": {
          "type": "string"
        },
        "messages": {
          "$ref": "#/definitions/ConfirmationFormMessages"
        },
        "title": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "ConfirmationFormMessages": {
      "additionalProperties": false,
      "properties": {
        "noCartItems": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "ElementObject": {
      "additionalProperties": false,
      "properties": {
        "color": {
          "type": "string"
        },
        "size": {
          "type": "number"
        },
        "weight": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnableObject<structure-1425356789-514-552-1425356789-500-553-1425356789-478-554-1425356789-311-556-1425356789-285-557-1425356789-0-558>": {
      "additionalProperties": false,
      "properties": {
        "enabled": {
          "type": "boolean"
        },
        "intervalTime": {
          "type": "number"
        }
      },
      "required": [
        "enabled"
      ],
      "type": "object"
    },
    "EnableValueObject": {
      "additionalProperties": false,
      "properties": {
        "enabled": {
          "type": "boolean"
        },
        "value": {
          "type": "string"
        }
      },
      "required": [
        "enabled"
      ],
      "type": "object"
    },
    "ExitIntentForm": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "type": "string"
        },
        "dismissButton": {
          "type": "string"
        },
        "footerText": {
          "type": "string"
        },
        "spinButton": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "InputField": {
      "additionalProperties": false,
      "properties": {
        "messages": {
          "additionalProperties": false,
          "properties": {
            "required": {
              "type": "string"
            },
            "type": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "placeholder": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "IntroBaseForm": {
      "additionalProperties": false,
      "type": "object"
    },
    "IntroForms": {
      "additionalProperties": false,
      "properties": {
        "base": {
          "$ref": "#/definitions/IntroBaseForm"
        },
        "exitIntentForm": {
          "$ref": "#/definitions/ExitIntentForm"
        },
        "welcomeForm": {
          "$ref": "#/definitions/WelcomeForm"
        }
      },
      "type": "object"
    },
    "IntroPopup": {
      "additionalProperties": false,
      "properties": {
        "backgroundImage": {
          "$ref": "#/definitions/BackgroundImage"
        },
        "backgroundOverlay": {
          "additionalProperties": false,
          "properties": {
            "color": {
              "type": "string"
            },
            "enabled": {
              "type": "boolean"
            }
          },
          "type": "object"
        },
        "forms": {
          "$ref": "#/definitions/IntroForms"
        }
      },
      "type": "object"
    },
    "OpenerDistance": {
      "additionalProperties": false,
      "properties": {
        "bottom": {
          "type": "number"
        },
        "bottomFromAnnouncement": {
          "type": "number"
        },
        "left": {
          "type": "number"
        },
        "right": {
          "type": "number"
        }
      },
      "type": "object"
    },
    "OpenerIcon": {
      "additionalProperties": false,
      "properties": {
        "deltaX": {
          "type": "number"
        },
        "deltaY": {
          "type": "number"
        },
        "transparentBackground": {
          "type": "boolean"
        },
        "value": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "OpenerPosition": {
      "enum": [
        "left",
        "right"
      ],
      "type": "string"
    },
    "PresetTheme": {
      "additionalProperties": false,
      "properties": {
        "announcement": {
          "$ref": "#/definitions/ThemeAnnouncement"
        },
        "id": {
          "type": "string"
        },
        "opener": {
          "$ref": "#/definitions/ThemeOpener"
        },
        "popups": {
          "$ref": "#/definitions/ThemePopups"
        },
        "revertedFrom": {
          "type": "string"
        },
        "rewardTypes": {
          "$ref": "#/definitions/ThemeRewardTypes"
        },
        "wheel": {
          "$ref": "#/definitions/ThemeWheel"
        }
      },
      "type": "object"
    },
    "ResultForm": {
      "additionalProperties": false,
      "properties": {
        "dismissButton": {
          "type": "string"
        },
        "messages": {
          "$ref": "#/definitions/ResultFormMessages"
        },
        "redeemButton": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "ResultFormMessages": {
      "additionalProperties": false,
      "properties": {
        "rewardExpiry": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "SpinBaseForm": {
      "additionalProperties": false,
      "properties": {
        "contentPanel": {
          "additionalProperties": false,
          "properties": {
            "backgroundColor": {
              "type": "string"
            },
            "blur": {
              "type": "string"
            },
            "displayed": {
              "type": "boolean"
            }
          },
          "type": "object"
        }
      },
      "type": "object"
    },
    "SpinForm": {
      "additionalProperties": false,
      "properties": {
        "agreement": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "descriptionForExistingAccount": {
          "type": "string"
        },
        "dismissButton": {
          "type": "string"
        },
        "fields": {
          "additionalProperties": {
            "$ref": "#/definitions/InputField"
          },
          "type": "object"
        },
        "footerText": {
          "type": "string"
        },
        "messages": {
          "$ref": "#/definitions/SpinFormMessages"
        },
        "spinButton": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "SpinFormMessages": {
      "additionalProperties": false,
      "properties": {
        "maxSpinReached": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "SpinForms": {
      "additionalProperties": false,
      "properties": {
        "base": {
          "$ref": "#/definitions/SpinBaseForm"
        },
        "confirmationForm": {
          "$ref": "#/definitions/ConfirmationForm"
        },
        "resultForm": {
          "$ref": "#/definitions/ResultForm"
        },
        "spinForm": {
          "$ref": "#/definitions/SpinForm"
        }
      },
      "required": [
        "spinForm",
        "resultForm",
        "confirmationForm"
      ],
      "type": "object"
    },
    "SpinPopup": {
      "additionalProperties": false,
      "properties": {
        "backgroundImage": {
          "$ref": "#/definitions/BackgroundImage"
        },
        "backgroundMusic": {
          "$ref": "#/definitions/EnableValueObject"
        },
        "displayType": {
          "$ref": "#/definitions/SpinPopupDisplayType"
        },
        "forms": {
          "$ref": "#/definitions/SpinForms"
        },
        "playingMusic": {
          "$ref": "#/definitions/EnableValueObject"
        },
        "showLogo": {
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "SpinPopupDisplayType": {
      "enum": [
        "auto",
        "full_screen"
      ],
      "type": "string"
    },
    "StorageObject": {
      "additionalProperties": false,
      "properties": {
        "key": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      },
      "required": [
        "key",
        "url"
      ],
      "type": "object"
    },
    "TextElement": {
      "additionalProperties": false,
      "properties": {
        "color": {
          "type": "string"
        },
        "size": {
          "type": "number"
        },
        "text": {
          "type": "string"
        },
        "weight": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "TextInputElement": {
      "additionalProperties": false,
      "properties": {
        "backgroundColor": {
          "type": "string"
        },
        "color": {
          "type": "string"
        },
        "placeholderColor": {
          "type": "string"
        },
        "size": {
          "type": "number"
        },
        "weight": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "ThemeAnnouncement": {
      "additionalProperties": false,
      "properties": {
        "backgroundColor": {
          "type": "string"
        },
        "color": {
          "type": "string"
        },
        "encourageMessages": {
          "$ref": "#/definitions/AnnouncementEncourageMessages"
        },
        "fontFamily": {
          "type": "string"
        },
        "messages": {
          "$ref": "#/definitions/AnnouncementMessages"
        },
        "position": {
          "$ref": "#/definitions/AnnouncementPosition"
        },
        "size": {
          "type": "number"
        },
        "weight": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "ThemeOpener": {
      "additionalProperties": false,
      "properties": {
        "attentionEffect": {
          "$ref": "#/definitions/EnableObject%3Cstructure-1425356789-514-552-1425356789-500-553-1425356789-478-554-1425356789-311-556-1425356789-285-557-1425356789-0-558%3E"
        },
        "backgroundColor": {
          "type": "string"
        },
        "distance": {
          "$ref": "#/definitions/OpenerDistance"
        },
        "fontFamily": {
          "type": "string"
        },
        "icon": {
          "$ref": "#/definitions/OpenerIcon"
        },
        "label": {
          "$ref": "#/definitions/TextElement"
        },
        "position": {
          "$ref": "#/definitions/OpenerPosition"
        }
      },
      "type": "object"
    },
    "ThemePopups": {
      "additionalProperties": false,
      "properties": {
        "base": {
          "$ref": "#/definitions/BasePopup"
        },
        "introPopup": {
          "$ref": "#/definitions/IntroPopup"
        },
        "spinPopup": {
          "$ref": "#/definitions/SpinPopup"
        }
      },
      "type": "object"
    },
    "ThemeRewardMessage": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "ThemeRewardTypeItem": {
      "additionalProperties": false,
      "properties": {
        "effectMusic": {
          "$ref": "#/definitions/EnableValueObject"
        },
        "message": {
          "$ref": "#/definitions/ThemeRewardMessage"
        }
      },
      "type": "object"
    },
    "ThemeRewardTypes": {
      "additionalProperties": false,
      "properties": {
        "discountCode": {
          "$ref": "#/definitions/ThemeRewardTypeItem"
        },
        "freeGift": {
          "$ref": "#/definitions/ThemeRewardTypeItem"
        },
        "freeShipping": {
          "$ref": "#/definitions/ThemeRewardTypeItem"
        },
        "none": {
          "$ref": "#/definitions/ThemeRewardTypeItem"
        }
      },
      "type": "object"
    },
    "ThemeWheel": {
      "additionalProperties": false,
      "properties": {
        "border": {
          "$ref": "#/definitions/WheelBorder"
        },
        "center": {
          "$ref": "#/definitions/WheelCenter"
        },
        "fontFamily": {
          "type": "string"
        },
        "pointer": {
          "$ref": "#/definitions/WheelPointer"
        },
        "size": {
          "type": "number"
        },
        "slices": {
          "$ref": "#/definitions/WheelSlices"
        }
      },
      "type": "object"
    },
    "WelcomeForm": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "type": "string"
        },
        "dismissButton": {
          "type": "string"
        },
        "footerText": {
          "type": "string"
        },
        "spinButton": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "WheelBorder": {
      "additionalProperties": false,
      "properties": {
        "color": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/WheelBorderType"
        }
      },
      "type": "object"
    },
    "WheelBorderType": {
      "enum": [
        "none",
        "line",
        "auto_darken"
      ],
      "type": "string"
    },
    "WheelCenter": {
      "additionalProperties": false,
      "properties": {
        "border": {
          "$ref": "#/definitions/WheelCenterBorder"
        },
        "color": {
          "type": "string"
        },
        "displayed": {
          "type": "boolean"
        },
        "icon": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "WheelCenterBorder": {
      "additionalProperties": false,
      "properties": {
        "color": {
          "type": "string"
        },
        "displayed": {
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "WheelPointer": {
      "additionalProperties": false,
      "properties": {
        "border": {
          "$ref": "#/definitions/WheelPointerBorder"
        },
        "color": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "WheelPointerBorder": {
      "additionalProperties": false,
      "properties": {
        "color": {
          "type": "string"
        },
        "displayed": {
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "WheelSlices": {
      "additionalProperties": false,
      "properties": {
        "border": {
          "$ref": "#/definitions/WheelSlicesBorder"
        },
        "items": {
          "items": {
            "$ref": "#/definitions/WheelSlicesItem"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "WheelSlicesBorder": {
      "additionalProperties": false,
      "properties": {
        "color": {
          "type": "string"
        },
        "displayed": {
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "WheelSlicesItem": {
      "additionalProperties": false,
      "properties": {
        "backgroundColor": {
          "type": "string"
        },
        "color": {
          "type": "string"
        }
      },
      "type": "object"
    }
  }
}

=== eplugin-io/spinx/catalog/classic/themes/CLS_05/theme.json
{
  "id": "CLS_05",
  "wheel": {
    "border": {
      "type": "line",
      "color": "#dcba02"
    },
    "center": {
      "displayed": true,
      "border": {
        "displayed": true,
        "color": "#FFD700"
      },
      "color": "#FFD700"
    },
    "pointer": {
      "color": "#FFD700",
      "border": {
        "displayed": false,
        "color": ""
      }
    },
    "slices": {
      "border": {
        "displayed": true,
        "color": "#dcba02"
      },
      "items": [
        {
          "color": "#E5E4E2",
          "backgroundColor": "#4B0082"
        },
        {
          "color": "#E5E4E2",
          "backgroundColor": "#2E0854"
        }
      ]
    }
  },
  "opener": {
    "icon": {
      "value": "CLS_11"
    },
    "label": {
      "color": "#FFD700"
    },
    "backgroundColor": "#2E0854"
  },
  "popups": {
    "base": {
      "backgroundColor": "#380062",
      "title": {
        "color": "#FFD700"
      },
      "description": {
        "color": "#ffffff"
      },
      "textInput": {
        "color": "#ffffff"
      },
      "helper": {
        "color": "#ffffff"
      },
      "footer": {
        "color": "#ffffff"
      },
      "primaryButton": {
        "color": "#4B0082",
        "backgroundColor": "#E6C200"
      },
      "secondaryButton": {
        "color": "#ffffff"
      },
      "linkButton": {
        "color": "#ffffff"
      }
    },
    "spinPopup": {
      "backgroundImage": {}
    },
    "introPopup": {
      "backgroundImage": {},
      "backgroundOverlay": {}
    }
  },
  "announcement": {
    "color": "#FFD700",
    "backgroundColor": "#4B0082"
  }
}

=== eplugin-io/spinx/catalog/halloween/themes/HLW_02/theme.json
{
  "rewardTypes": {
    "none": {
      "message": {
        "title": "Oops! Maybe next time ☠️",
        "description": "The spirits stayed quiet this time. Thanks for spinning, see you next time!"
      },
      "effectMusic": {
        "enabled": true,
        "value": "HLW_LS_01"
      }
    },
    "discountCode": {
      "message": {
        "title": "🎃 Boo! You Won {{REWARD}}!",
        "description": "Use the code to feed your haunted cart with spooky savings."
      },
      "effectMusic": {
        "enabled": true,
        "value": "HLW_WN_01"
      }
    },
    "freeShipping": {
      "message": {
        "title": "🎃 Boo! You Won {{REWARD}}!",
        "description": "Free shipping is arriving straight from the other side."
      },
      "effectMusic": {
        "enabled": true,
        "value": "HLW_WN_01"
      }
    },
    "freeGift": {
      "message": {
        "title": "🎃 Boo! You Won {{REWARD}}!",
        "description": "The free gift is sealed in cobwebs—claim it before midnight."
      },
      "effectMusic": {
        "enabled": true,
        "value": "HLW_WN_02"
      }
    }
  },
  "opener": {
    "label": {
      "text": "SUMMON REWARD",
      "color": "#FFB84D"
    },
    "icon": {
      "value": "HLW_15",
      "deltaY": -3,
      "transparentBackground": true
    },
    "fontFamily": "Eater",
    "backgroundColor": "#0e0314"
  },
  "popups": {
    "spinPopup": {
      "forms": {
        "spinForm": {
          "title": "🎃 Dare to Spin... If You're Brave Enough!",
          "description": "Summon your prize by entering your name & email... if the spirits will it...",
          "descriptionForExistingAccount": "Hey {{NAME}}... One brave spin seals the ritual — spooky surprises await.",
          "agreement": "I agree to receive spooky updates and offers.",
          "spinButton": "Spin...if you dare!",
          "dismissButton": "Too Spooky, Keep Shopping",
          "footerText": "Only brave souls unlock the prize.",
          "messages": {
            "maxSpinReached": "The spirits say you've spun enough for now."
          }
        },
        "resultForm": {},
        "confirmationForm": {
          "title": "Spooky Win Locked In!"
        }
      },
      "displayType": "full_screen",
      "showLogo": false,
      "backgroundImage": {
        "main": {
          "key": "",
          "url": "/catalog/halloween/themes/HLW_02/background/main.webp"
        },
        "mobile": {
          "key": "",
          "url": "/catalog/halloween/themes/HLW_02/background/main-mobile.webp"
        }
      },
      "backgroundMusic": {
        "enabled": true,
        "value": "HLW_BG_03"
      },
      "playingMusic": {
        "enabled": true,
        "value": "HLW_PY_02"
      }
    },
    "introPopup": {
      "forms": {
        "welcomeForm": {
          "title": "🎃 A Spooktacular Treat Awaits!",
          "description": "Spin the haunted wheel to uncover chilling discounts, free shipping... and maybe a trick or two ☠️",
          "footerText": "Spin the wheel and claim your special reward.",
          "spinButton": "Trick or Treat Me",
          "dismissButton": "Too Spooky, Skip"
        },
        "exitIntentForm": {
          "title": "🎃 A Spooktacular Treat Awaits!",
          "description": "Spin the haunted wheel to uncover chilling discounts, free shipping... and maybe a trick or two ☠️",
          "footerText": "Spin the wheel and claim your special reward.",
          "spinButton": "Trick or Treat Me",
          "dismissButton": "Too Spooky, Skip"
        }
      },
      "backgroundImage": {
        "main": {
          "key": "",
          "url": "/catalog/halloween/themes/HLW_02/background/intro.webp"
        },
        "mobile": {
          "key": "",
          "url": "/catalog/halloween/themes/HLW_02/background/intro-mobile.webp"
        }
      },
      "backgroundOverlay": {}
    },
    "base": {
      "backgroundColor": "#ffffff",
      "fontFamily": "Special Elite",
      "title": {
        "color": "#FFB84D"
      },
      "description": {
        "color": "#E0E0E0"
      },
      "textInput": {
        "color": "#FFFFFF",
        "backgroundColor": "rgb(72 45 76 / 62%)",
        "placeholderColor": "#AAAAAA"
      },
      "helper": {
        "color": "#E0E0E0"
      },
      "footer": {
        "color": "#E0E0E0"
      },
      "primaryButton": {
        "color": "#FFFFFF",
        "backgroundColor": "#da600e"
      },
      "secondaryButton": {
        "color": "#DDDDDD",
        "backgroundColor": "rgba(255,255,255,0.10)"
      },
      "linkButton": {
        "color": "#E0E0E0"
      }
    }
  },
  "announcement": {
    "messages": {
      "upcomingEvent": "🎃 Spirits whisper... The wheel will spin at {{TIME}}. Be prepared!",
      "readyToSpin": "Trick or Treat? Click {{OPENER}} to Spin & Claim Your Reward!",
      "countDownToLaunch": "🎃 Get your courage ready... Wheel unlocks in {{TIME}}!",
      "countDownToClose": "🎃 Last chance! {{TIME}} left to spin the haunted wheel — don't miss it!"
    },
    "fontFamily": "Nosifer",
    "color": "#FFB84D",
    "backgroundColor": "#20072d"
  },
  "id": "HLW_02",
  "wheel": {
    "fontFamily": "Special Elite",
    "border": {
      "type": "line",
      "color": "#FF9933"
    },
    "center": {
      "displayed": true,
      "border": {
        "displayed": true,
        "color": "#FF9933"
      },
      "color": "#FF7518"
    },
    "pointer": {
      "color": "#FF7518",
      "border": {
        "displayed": true,
        "color": "#FF9933"
      }
    },
    "slices": {
      "border": {
        "displayed": true,
        "color": "#FF9933"
      },
      "items": [
        {
          "color": "#DDDDDD",
          "backgroundColor": "#E67E22"
        },
        {
          "color": "#DDDDDD",
          "backgroundColor": "#170B20"
        }
      ]
    }
  }
}

=== eplugin-io/spinx/catalog/classic/themes/CLS_19/theme.json
{
  "id": "CLS_19",
  "wheel": {
    "border": {
      "type": "line",
      "color": "#FFD700"
    },
    "center": {
      "displayed": true,
      "border": {
        "displayed": true,
        "color": "#F8D47D"
      },
      "color": "#FFD700"
    },
    "pointer": {
      "color": "#FFD700",
      "border": {
        "displayed": true,
        "color": "#F8D47D"
      }
    },
    "slices": {
      "border": {
        "displayed": true,
        "color": "#FFD700"
      },
      "items": [
        {
          "color": "#F5F5DC",
          "backgroundColor": "#7B3F00"
        },
        {
          "color": "#F5F5DC",
          "backgroundColor": "#3E2723"
        }
      ]
    }
  },
  "opener": {
    "icon": {
      "value": "CLS_07"
    },
    "label": {
      "color": "#FFD700"
    },
    "backgroundColor": "#3E2723"
  },
  "popups": {
    "base": {
      "backgroundColor": "#3E2723",
      "title": {
        "color": "#FFD700"
      },
      "description": {
        "color": "#F5F5DC"
      },
      "textInput": {
        "color": "#F5F5DC"
      },
      "helper": {
        "color": "#F5F5DC"
      },
      "footer": {
        "color": "#F5F5DC"
      },
      "primaryButton": {
        "color": "#5e3001",
        "backgroundColor": "#FFD700"
      },
      "secondaryButton": {
        "color": "#F5F5DC"
      },
      "linkButton": {
        "color": "#F5F5DC"
      }
    },
    "spinPopup": {
      "backgroundImage": {}
    },
    "introPopup": {
      "backgroundImage": {},
      "backgroundOverlay": {}
    }
  },
  "announcement": {
    "color": "#FFD700",
    "backgroundColor": "#7B3F00"
  }
}

=== eplugin-io/spinx/catalog/classic/themes/CLS_07/theme.json
{
  "id": "CLS_07",
  "wheel": {
    "border": {
      "type": "line",
      "color": "#C0C0C0"
    },
    "center": {
      "displayed": true,
      "border": {
        "displayed": true,
        "color": "#C0C0C0"
      },
      "color": "#C0C0C0"
    },
    "pointer": {
      "color": "#C0C0C0",
      "border": {
        "displayed": true,
        "color": "#666666"
      }
    },
    "slices": {
      "border": {
        "displayed": true,
        "color": "#C0C0C0"
      },
      "items": [
        {
          "color": "#FFFFFF",
          "backgroundColor": "#003366"
        },
        {
          "color": "#FFFFFF",
          "backgroundColor": "#001F54"
        }
      ]
    }
  },
  "opener": {
    "icon": {
      "value": "CLS_01"
    },
    "label": {
      "color": "#FFFFFF"
    },
    "backgroundColor": "#003366"
  },
  "popups": {
    "base": {
      "backgroundColor": "#001F54",
      "title": {
        "color": "#C0C0C0"
      },
      "description": {
        "color": "#FFFFFF"
      },
      "textInput": {
        "color": "#FFFFFF"
      },
      "helper": {
        "color": "#FFFFFF"
      },
      "footer": {
        "color": "#FFFFFF"
      },
      "primaryButton": {
        "color": "#FFFFFF",
        "backgroundColor": "#003a74"
      },
      "secondaryButton": {
        "color": "#FFFFFF"
      },
      "linkButton": {
        "color": "#FFFFFF"
      }
    },
    "spinPopup": {
      "backgroundImage": {}
    },
    "introPopup": {
      "backgroundImage": {},
      "backgroundOverlay": {}
    }
  },
  "announcement": {
    "color": "#C0C0C0",
    "backgroundColor": "#001F54"
  }
}
